{ "drinks": ( { 
"idDrink": "11008", 
"strDrink": "Manhattan", 
"strDrinkAlternate": null, 
"strDrinkES": null, 
"strDrinkDE": null, 
"strDrinkFR": null, 
"strDrinkZH-HANS": null, 
"strDrinkZH-HANT": null, 
"strTags": "IBA,Classic", 
"strVideo": null, 
"strCategory": "Cocktail", 
"strIBA": "Unforgettables", 
"strAlcoholic": "Alcoholic", 
"strGlass": "Cocktail glass", 
"strInstructions": "Stirred over ice, strained into a chilled glass, garnished, and served up.", 
"strInstructionsES": null, 
"strInstructionsDE": null, 
"strInstructionsFR": null, 
"strInstructionsZH-HANS": null, 
"strInstructionsZH-HANT": null, 
"strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/ec2jtz1504350429.jpg", 
"strIngredient1": "Sweet Vermouth", 
"strIngredient2": "Bourbon", 
"strIngredient3": "Angostura bitters", 
"strIngredient4": "Ice", 
"strIngredient5": "Maraschino cherry", 
"strIngredient6": "Orange peel", 
"strIngredient7": "", 
"strIngredient8": "", 
"strIngredient9": "", 
"strIngredient10": "", 
"strIngredient11": "", 
"strIngredient12": "", 
"strIngredient13": "", 
"strIngredient14": "", 
"strIngredient15": "", 
"strMeasure1": "3/4 oz ", 
"strMeasure2": "2 1/2 oz Blended ", 
"strMeasure3": "dash ", 
"strMeasure4": "2 or 3 ", 
"strMeasure5": "1 ", 
"strMeasure6": "1 twist of ", 
"strMeasure7": " ", 
"strMeasure8": " ", 
"strMeasure9": " ", 
"strMeasure10": " ", 
"strMeasure11": " ", 
"strMeasure12": "", 
"strMeasure13": "", 
"strMeasure14": "", 
"strMeasure15": "", 
"dateModified": "2017-09-02 12:07:09" } ) }